import type { Monaco } from "@monaco-editor/react";

interface PhpFunction {
  label: string;
  detail: string;
  documentation: string;
}

const PHP_FUNCTIONS: PhpFunction[] = [
  // ── String ──
  { label: "strlen", detail: "strlen(string $string): int", documentation: "Returns the length of a string." },
  { label: "strpos", detail: "strpos(string $haystack, string $needle, int $offset = 0): int|false", documentation: "Finds the position of the first occurrence of a substring." },
  { label: "strrpos", detail: "strrpos(string $haystack, string $needle, int $offset = 0): int|false", documentation: "Finds the position of the last occurrence of a substring." },
  { label: "stripos", detail: "stripos(string $haystack, string $needle, int $offset = 0): int|false", documentation: "Case-insensitive strpos." },
  { label: "str_replace", detail: "str_replace(mixed $search, mixed $replace, mixed $subject, int &$count = null): mixed", documentation: "Replaces all occurrences of the search string with the replacement string." },
  { label: "str_ireplace", detail: "str_ireplace(mixed $search, mixed $replace, mixed $subject, int &$count = null): mixed", documentation: "Case-insensitive version of str_replace." },
  { label: "substr", detail: "substr(string $string, int $offset, ?int $length = null): string", documentation: "Returns part of a string." },
  { label: "substr_count", detail: "substr_count(string $haystack, string $needle, int $offset = 0, ?int $length = null): int", documentation: "Counts the number of substring occurrences." },
  { label: "strtolower", detail: "strtolower(string $string): string", documentation: "Makes a string lowercase." },
  { label: "strtoupper", detail: "strtoupper(string $string): string", documentation: "Makes a string uppercase." },
  { label: "ucfirst", detail: "ucfirst(string $string): string", documentation: "Makes the first character uppercase." },
  { label: "lcfirst", detail: "lcfirst(string $string): string", documentation: "Makes the first character lowercase." },
  { label: "ucwords", detail: "ucwords(string $string, string $separators = \" \\t\\r\\n\\f\"): string", documentation: "Uppercases the first character of each word." },
  { label: "trim", detail: "trim(string $string, string $characters = \" \\t\\n\\r\\0\\x0B\"): string", documentation: "Strips whitespace from the beginning and end of a string." },
  { label: "ltrim", detail: "ltrim(string $string, string $characters = \" \\t\\n\\r\\0\\x0B\"): string", documentation: "Strips whitespace from the beginning of a string." },
  { label: "rtrim", detail: "rtrim(string $string, string $characters = \" \\t\\n\\r\\0\\x0B\"): string", documentation: "Strips whitespace from the end of a string." },
  { label: "explode", detail: "explode(string $separator, string $string, int $limit = PHP_INT_MAX): array", documentation: "Splits a string by a separator." },
  { label: "implode", detail: "implode(string $separator, array $array): string", documentation: "Joins array elements with a string." },
  { label: "str_split", detail: "str_split(string $string, int $length = 1): array", documentation: "Converts a string to an array." },
  { label: "str_pad", detail: "str_pad(string $string, int $length, string $pad_string = \" \", int $pad_type = STR_PAD_RIGHT): string", documentation: "Pads a string to a certain length." },
  { label: "str_repeat", detail: "str_repeat(string $string, int $times): string", documentation: "Repeats a string." },
  { label: "str_word_count", detail: "str_word_count(string $string, int $format = 0, ?string $characters = null): int|array", documentation: "Counts the number of words in a string." },
  { label: "str_contains", detail: "str_contains(string $haystack, string $needle): bool", documentation: "Checks if a string contains a given substring." },
  { label: "str_starts_with", detail: "str_starts_with(string $haystack, string $needle): bool", documentation: "Checks if a string starts with a given substring." },
  { label: "str_ends_with", detail: "str_ends_with(string $haystack, string $needle): bool", documentation: "Checks if a string ends with a given substring." },
  { label: "strcmp", detail: "strcmp(string $string1, string $string2): int", documentation: "Binary safe string comparison." },
  { label: "strcasecmp", detail: "strcasecmp(string $string1, string $string2): int", documentation: "Case-insensitive string comparison." },
  { label: "nl2br", detail: "nl2br(string $string, bool $use_xhtml = true): string", documentation: "Inserts HTML line breaks before all newlines." },
  { label: "htmlspecialchars", detail: "htmlspecialchars(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, ?string $encoding = null, bool $double_encode = true): string", documentation: "Converts special characters to HTML entities." },
  { label: "htmlentities", detail: "htmlentities(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, ?string $encoding = null, bool $double_encode = true): string", documentation: "Converts all applicable characters to HTML entities." },
  { label: "htmlspecialchars_decode", detail: "htmlspecialchars_decode(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE): string", documentation: "Converts HTML entities back to special characters." },
  { label: "strip_tags", detail: "strip_tags(string $string, array|string|null $allowed_tags = null): string", documentation: "Strips HTML and PHP tags from a string." },
  { label: "addslashes", detail: "addslashes(string $string): string", documentation: "Quotes a string with backslashes." },
  { label: "stripslashes", detail: "stripslashes(string $string): string", documentation: "Removes backslashes from a string." },
  { label: "md5", detail: "md5(string $string, bool $binary = false): string", documentation: "Calculates the MD5 hash of a string." },
  { label: "sha1", detail: "sha1(string $string, bool $binary = false): string", documentation: "Calculates the SHA-1 hash of a string." },
  { label: "base64_encode", detail: "base64_encode(string $string): string", documentation: "Encodes data with MIME base64." },
  { label: "base64_decode", detail: "base64_decode(string $string, bool $strict = false): string|false", documentation: "Decodes data encoded with MIME base64." },
  { label: "urlencode", detail: "urlencode(string $string): string", documentation: "URL-encodes a string." },
  { label: "urldecode", detail: "urldecode(string $string): string", documentation: "Decodes a URL-encoded string." },
  { label: "rawurlencode", detail: "rawurlencode(string $string): string", documentation: "URL-encodes a string according to RFC 3986." },
  { label: "rawurldecode", detail: "rawurldecode(string $string): string", documentation: "Decodes a URL-encoded string." },
  { label: "number_format", detail: "number_format(float $num, int $decimals = 0, ?string $decimal_separator = \".\", ?string $thousands_separator = \",\"): string", documentation: "Formats a number with grouped thousands." },
  { label: "sprintf", detail: "sprintf(string $format, mixed ...$values): string", documentation: "Returns a formatted string." },
  { label: "printf", detail: "printf(string $format, mixed ...$values): int", documentation: "Outputs a formatted string." },
  { label: "wordwrap", detail: "wordwrap(string $string, int $width = 75, string $break = \"\\n\", bool $cut_long_words = false): string", documentation: "Wraps a string to a given number of characters." },
  { label: "str_getcsv", detail: "str_getcsv(string $string, string $separator = \",\", string $enclosure = '\"', string $escape = \"\\\\\"): array", documentation: "Parses a CSV string into an array." },
  { label: "chunk_split", detail: "chunk_split(string $string, int $length = 76, string $separator = \"\\r\\n\"): string", documentation: "Splits a string into smaller chunks." },
  { label: "quoted_printable_encode", detail: "quoted_printable_encode(string $string): string", documentation: "Converts a string to quoted-printable encoding." },

  // ── Array ──
  { label: "array_push", detail: "array_push(array &$array, mixed ...$values): int", documentation: "Pushes one or more elements onto the end of an array." },
  { label: "array_pop", detail: "array_pop(array &$array): mixed", documentation: "Pops the element off the end of array." },
  { label: "array_shift", detail: "array_shift(array &$array): mixed", documentation: "Shifts an element off the beginning of array." },
  { label: "array_unshift", detail: "array_unshift(array &$array, mixed ...$values): int", documentation: "Prepends one or more elements to the beginning of an array." },
  { label: "array_map", detail: "array_map(?callable $callback, array $array, array ...$arrays): array", documentation: "Applies a callback to the elements of given arrays." },
  { label: "array_filter", detail: "array_filter(array $array, ?callable $callback = null, int $mode = 0): array", documentation: "Filters elements of an array using a callback." },
  { label: "array_reduce", detail: "array_reduce(array $array, callable $callback, mixed $initial = null): mixed", documentation: "Reduces an array to a single value using a callback." },
  { label: "array_merge", detail: "array_merge(array ...$arrays): array", documentation: "Merges one or more arrays." },
  { label: "array_combine", detail: "array_combine(array $keys, array $values): array", documentation: "Creates an array by using one array for keys and another for values." },
  { label: "array_keys", detail: "array_keys(array $array, mixed $filter_value = null, bool $strict = false): array", documentation: "Returns all the keys of an array." },
  { label: "array_values", detail: "array_values(array $array): array", documentation: "Returns all the values of an array." },
  { label: "array_unique", detail: "array_unique(array $array, int $flags = SORT_STRING): array", documentation: "Removes duplicate values from an array." },
  { label: "array_reverse", detail: "array_reverse(array $array, bool $preserve_keys = false): array", documentation: "Returns an array with elements in reverse order." },
  { label: "array_flip", detail: "array_flip(array $array): array", documentation: "Exchanges all keys with their associated values." },
  { label: "array_slice", detail: "array_slice(array $array, int $offset, ?int $length = null, bool $preserve_keys = false): array", documentation: "Extracts a slice of the array." },
  { label: "array_splice", detail: "array_splice(array &$array, int $offset, ?int $length = null, mixed $replacement = []): array", documentation: "Removes and replaces part of an array." },
  { label: "array_chunk", detail: "array_chunk(array $array, int $length, bool $preserve_keys = false): array", documentation: "Splits an array into chunks." },
  { label: "array_search", detail: "array_search(mixed $needle, array $haystack, bool $strict = false): int|string|false", documentation: "Searches the array for a given value and returns the corresponding key." },
  { label: "array_column", detail: "array_column(array $array, int|string|null $column_key, int|string|null $index_key = null): array", documentation: "Returns the values from a single column." },
  { label: "array_fill", detail: "array_fill(int $start_index, int $count, mixed $value): array", documentation: "Fills an array with values." },
  { label: "array_fill_keys", detail: "array_fill_keys(array $keys, mixed $value): array", documentation: "Fills an array with values, specifying keys." },
  { label: "array_intersect", detail: "array_intersect(array $array, array ...$arrays): array", documentation: "Computes the intersection of arrays." },
  { label: "array_diff", detail: "array_diff(array $array, array ...$arrays): array", documentation: "Computes the difference of arrays." },
  { label: "array_diff_key", detail: "array_diff_key(array $array, array ...$arrays): array", documentation: "Computes the difference of arrays using keys for comparison." },
  { label: "array_key_exists", detail: "array_key_exists(string|int $key, array $array): bool", documentation: "Checks if the given key or index exists in the array." },
  { label: "array_walk", detail: "array_walk(array &$array, callable $callback, mixed $arg = null): true", documentation: "Applies a user function to every member of an array." },
  { label: "array_sum", detail: "array_sum(array $array): int|float", documentation: "Calculates the sum of values in an array." },
  { label: "array_product", detail: "array_product(array $array): int|float", documentation: "Calculates the product of values in an array." },
  { label: "array_count_values", detail: "array_count_values(array $array): array", documentation: "Counts the occurrences of each distinct value." },
  { label: "array_pad", detail: "array_pad(array $array, int $length, mixed $value): array", documentation: "Pads an array to the specified length with a value." },
  { label: "array_rand", detail: "array_rand(array $array, int $num = 1): int|string|array", documentation: "Picks one or more random keys from an array." },
  { label: "array_multisort", detail: "array_multisort(array &$array, mixed ...$rest): bool", documentation: "Sorts multiple arrays or multi-dimensional arrays." },
  { label: "count", detail: "count(Countable|array $value, int $mode = COUNT_NORMAL): int", documentation: "Counts all elements in an array or Countable object." },
  { label: "sizeof", detail: "sizeof(Countable|array $value, int $mode = COUNT_NORMAL): int", documentation: "Alias of count." },
  { label: "in_array", detail: "in_array(mixed $needle, array $haystack, bool $strict = false): bool", documentation: "Checks if a value exists in an array." },
  { label: "sort", detail: "sort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array in ascending order." },
  { label: "rsort", detail: "rsort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array in descending order." },
  { label: "asort", detail: "asort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array maintaining index association." },
  { label: "arsort", detail: "arsort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array in reverse order maintaining index association." },
  { label: "ksort", detail: "ksort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array by key in ascending order." },
  { label: "krsort", detail: "krsort(array &$array, int $flags = SORT_REGULAR): true", documentation: "Sorts an array by key in descending order." },
  { label: "usort", detail: "usort(array &$array, callable $callback): true", documentation: "Sorts an array by values using a user-defined comparison function." },
  { label: "uasort", detail: "uasort(array &$array, callable $callback): true", documentation: "Sorts an array with a user-defined comparison function, maintaining key association." },
  { label: "uksort", detail: "uksort(array &$array, callable $callback): true", documentation: "Sorts an array by keys using a user-defined comparison function." },
  { label: "compact", detail: "compact(array|string $var_name, array|string ...$var_names): array", documentation: "Creates an array containing variables and their values." },
  { label: "extract", detail: "extract(array &$array, int $flags = EXTR_OVERWRITE, string $prefix = \"\"): int", documentation: "Imports variables from an array into the current symbol table." },
  { label: "list", detail: "list(mixed ...$vars): array", documentation: "Assigns variables as if they were an array." },
  { label: "range", detail: "range(string|int|float $start, string|int|float $end, int|float $step = 1): array", documentation: "Creates an array containing a range of elements." },

  // ── Math ──
  { label: "abs", detail: "abs(int|float $num): int|float", documentation: "Returns the absolute value." },
  { label: "ceil", detail: "ceil(int|float $num): float", documentation: "Rounds up to the nearest integer." },
  { label: "floor", detail: "floor(int|float $num): float", documentation: "Rounds down to the nearest integer." },
  { label: "round", detail: "round(int|float $num, int $precision = 0, int $mode = PHP_ROUND_HALF_UP): float", documentation: "Rounds a float." },
  { label: "max", detail: "max(mixed $value, mixed ...$values): mixed", documentation: "Finds the highest value." },
  { label: "min", detail: "min(mixed $value, mixed ...$values): mixed", documentation: "Finds the lowest value." },
  { label: "rand", detail: "rand(int $min = 0, int $max = getrandmax()): int", documentation: "Generates a random integer." },
  { label: "mt_rand", detail: "mt_rand(int $min = 0, int $max = mt_getrandmax()): int", documentation: "Generates a random integer via Mersenne Twister." },
  { label: "random_int", detail: "random_int(int $min, int $max): int", documentation: "Generates cryptographically secure random integers." },
  { label: "pow", detail: "pow(mixed $base, mixed $exp): int|float|object", documentation: "Exponential expression." },
  { label: "sqrt", detail: "sqrt(float $num): float", documentation: "Square root." },
  { label: "log", detail: "log(float $num, float $base = M_E): float", documentation: "Natural logarithm." },
  { label: "log10", detail: "log10(float $num): float", documentation: "Base-10 logarithm." },
  { label: "fmod", detail: "fmod(float $x, float $y): float", documentation: "Returns the floating point remainder of the division." },
  { label: "intdiv", detail: "intdiv(int $a, int $b): int", documentation: "Integer division." },
  { label: "pi", detail: "pi(): float", documentation: "Returns the value of pi." },

  // ── Date/Time ──
  { label: "date", detail: "date(string $format, ?int $timestamp = null): string", documentation: "Formats a local date/time." },
  { label: "time", detail: "time(): int", documentation: "Returns current Unix timestamp." },
  { label: "mktime", detail: "mktime(int $hour, ?int $minute = null, ?int $second = null, ?int $month = null, ?int $day = null, ?int $year = null): int|false", documentation: "Gets Unix timestamp for a date." },
  { label: "strtotime", detail: "strtotime(string $datetime, ?int $baseTimestamp = null): int|false", documentation: "Parses an English textual datetime description into a Unix timestamp." },
  { label: "date_create", detail: "date_create(string $datetime = \"now\", ?DateTimeZone $timezone = null): DateTime|false", documentation: "Creates a new DateTime object." },
  { label: "date_format", detail: "date_format(DateTimeInterface $object, string $format): string", documentation: "Returns date formatted according to given format." },
  { label: "date_diff", detail: "date_diff(DateTimeInterface $baseObject, DateTimeInterface $targetObject, bool $absolute = false): DateInterval", documentation: "Returns the difference between two DateTime objects." },
  { label: "date_modify", detail: "date_modify(DateTime $object, string $modifier): DateTime|false", documentation: "Alters the timestamp of a DateTime object." },
  { label: "getdate", detail: "getdate(?int $timestamp = null): array", documentation: "Gets date/time information." },
  { label: "checkdate", detail: "checkdate(int $month, int $day, int $year): bool", documentation: "Validates a Gregorian date." },
  { label: "microtime", detail: "microtime(bool $as_float = false): string|float", documentation: "Returns current Unix timestamp with microseconds." },

  // ── File ──
  { label: "fopen", detail: "fopen(string $filename, string $mode, bool $use_include_path = false, ?resource $context = null): resource|false", documentation: "Opens a file or URL." },
  { label: "fclose", detail: "fclose(resource $stream): bool", documentation: "Closes an open file pointer." },
  { label: "fread", detail: "fread(resource $stream, int $length): string|false", documentation: "Binary-safe file read." },
  { label: "fwrite", detail: "fwrite(resource $stream, string $data, ?int $length = null): int|false", documentation: "Binary-safe file write." },
  { label: "fgets", detail: "fgets(resource $stream, ?int $length = null): string|false", documentation: "Gets a line from file pointer." },
  { label: "feof", detail: "feof(resource $stream): bool", documentation: "Tests for end-of-file on a file pointer." },
  { label: "file_get_contents", detail: "file_get_contents(string $filename, bool $use_include_path = false, ?resource $context = null, int $offset = 0, ?int $length = null): string|false", documentation: "Reads entire file into a string." },
  { label: "file_put_contents", detail: "file_put_contents(string $filename, mixed $data, int $flags = 0, ?resource $context = null): int|false", documentation: "Writes data to a file." },
  { label: "file_exists", detail: "file_exists(string $filename): bool", documentation: "Checks whether a file or directory exists." },
  { label: "is_file", detail: "is_file(string $filename): bool", documentation: "Tells whether the filename is a regular file." },
  { label: "is_dir", detail: "is_dir(string $filename): bool", documentation: "Tells whether the filename is a directory." },
  { label: "mkdir", detail: "mkdir(string $directory, int $permissions = 0777, bool $recursive = false, ?resource $context = null): bool", documentation: "Makes a directory." },
  { label: "rmdir", detail: "rmdir(string $directory, ?resource $context = null): bool", documentation: "Removes a directory." },
  { label: "unlink", detail: "unlink(string $filename, ?resource $context = null): bool", documentation: "Deletes a file." },
  { label: "rename", detail: "rename(string $from, string $to, ?resource $context = null): bool", documentation: "Renames a file or directory." },
  { label: "copy", detail: "copy(string $from, string $to, ?resource $context = null): bool", documentation: "Copies a file." },
  { label: "glob", detail: "glob(string $pattern, int $flags = 0): array|false", documentation: "Finds pathnames matching a pattern." },
  { label: "realpath", detail: "realpath(string $path): string|false", documentation: "Returns canonicalized absolute pathname." },
  { label: "basename", detail: "basename(string $path, string $suffix = \"\"): string", documentation: "Returns trailing name component of a path." },
  { label: "dirname", detail: "dirname(string $path, int $levels = 1): string", documentation: "Returns a parent directory's path." },
  { label: "pathinfo", detail: "pathinfo(string $path, int $flags = PATHINFO_ALL): array|string", documentation: "Returns information about a file path." },
  { label: "filesize", detail: "filesize(string $filename): int|false", documentation: "Gets file size." },
  { label: "tempnam", detail: "tempnam(string $directory, string $prefix): string|false", documentation: "Creates a file with a unique filename." },
  { label: "scandir", detail: "scandir(string $directory, int $sorting_order = SCANDIR_SORT_ASCENDING, ?resource $context = null): array|false", documentation: "Lists files and directories inside the specified path." },

  // ── Type checking / casting ──
  { label: "isset", detail: "isset(mixed $var, mixed ...$vars): bool", documentation: "Determines if a variable is declared and is different than null." },
  { label: "unset", detail: "unset(mixed $var, mixed ...$vars): void", documentation: "Unsets a given variable." },
  { label: "empty", detail: "empty(mixed $var): bool", documentation: "Determines whether a variable is empty." },
  { label: "is_null", detail: "is_null(mixed $value): bool", documentation: "Checks whether a variable is null." },
  { label: "is_array", detail: "is_array(mixed $value): bool", documentation: "Checks whether a variable is an array." },
  { label: "is_string", detail: "is_string(mixed $value): bool", documentation: "Checks whether a variable is a string." },
  { label: "is_int", detail: "is_int(mixed $value): bool", documentation: "Checks whether a variable is an integer." },
  { label: "is_float", detail: "is_float(mixed $value): bool", documentation: "Checks whether a variable is a float." },
  { label: "is_bool", detail: "is_bool(mixed $value): bool", documentation: "Checks whether a variable is a boolean." },
  { label: "is_numeric", detail: "is_numeric(mixed $value): bool", documentation: "Checks whether a variable is a number or a numeric string." },
  { label: "is_object", detail: "is_object(mixed $value): bool", documentation: "Checks whether a variable is an object." },
  { label: "is_callable", detail: "is_callable(mixed $value, bool $syntax_only = false, ?string &$callable_name = null): bool", documentation: "Checks whether a value can be called as a function." },
  { label: "gettype", detail: "gettype(mixed $value): string", documentation: "Gets the type of a variable." },
  { label: "settype", detail: "settype(mixed &$var, string $type): bool", documentation: "Sets the type of a variable." },
  { label: "intval", detail: "intval(mixed $value, int $base = 10): int", documentation: "Gets the integer value of a variable." },
  { label: "floatval", detail: "floatval(mixed $value): float", documentation: "Gets the float value of a variable." },
  { label: "strval", detail: "strval(mixed $value): string", documentation: "Gets the string value of a variable." },
  { label: "boolval", detail: "boolval(mixed $value): bool", documentation: "Gets the boolean value of a variable." },
  { label: "var_export", detail: "var_export(mixed $value, bool $return = false): ?string", documentation: "Outputs or returns a parsable string representation of a variable." },

  // ── JSON ──
  { label: "json_encode", detail: "json_encode(mixed $value, int $flags = 0, int $depth = 512): string|false", documentation: "Returns the JSON representation of a value." },
  { label: "json_decode", detail: "json_decode(string $json, ?bool $associative = null, int $depth = 512, int $flags = 0): mixed", documentation: "Decodes a JSON string." },
  { label: "json_last_error", detail: "json_last_error(): int", documentation: "Returns the last error occurred during JSON encoding/decoding." },
  { label: "json_last_error_msg", detail: "json_last_error_msg(): string", documentation: "Returns the error string of the last json_encode() or json_decode() call." },

  // ── Regex ──
  { label: "preg_match", detail: "preg_match(string $pattern, string $subject, ?array &$matches = null, int $flags = 0, int $offset = 0): int|false", documentation: "Performs a regular expression match." },
  { label: "preg_match_all", detail: "preg_match_all(string $pattern, string $subject, ?array &$matches = null, int $flags = 0, int $offset = 0): int|false", documentation: "Performs a global regular expression match." },
  { label: "preg_replace", detail: "preg_replace(string|array $pattern, string|array $replacement, string|array $subject, int $limit = -1, ?int &$count = null): string|array|null", documentation: "Performs a regular expression search and replace." },
  { label: "preg_replace_callback", detail: "preg_replace_callback(string|array $pattern, callable $callback, string|array $subject, int $limit = -1, ?int &$count = null, int $flags = 0): string|array|null", documentation: "Performs a regular expression search and replace using a callback." },
  { label: "preg_split", detail: "preg_split(string $pattern, string $subject, int $limit = -1, int $flags = 0): array|false", documentation: "Splits a string by a regular expression." },
  { label: "preg_quote", detail: "preg_quote(string $str, ?string $delimiter = null): string", documentation: "Quotes regular expression characters." },

  // ── Output ──
  { label: "echo", detail: "echo(string ...$expressions): void", documentation: "Outputs one or more strings." },
  { label: "print", detail: "print(string $expression): int", documentation: "Outputs a string." },
  { label: "var_dump", detail: "var_dump(mixed $value, mixed ...$values): void", documentation: "Dumps information about a variable." },
  { label: "print_r", detail: "print_r(mixed $value, bool $return = false): string|true", documentation: "Prints human-readable information about a variable." },
  { label: "header", detail: "header(string $header, bool $replace = true, int $response_code = 0): void", documentation: "Sends a raw HTTP header." },
  { label: "http_response_code", detail: "http_response_code(int $response_code = 0): int|bool", documentation: "Gets or sets the HTTP response status code." },

  // ── Misc ──
  { label: "die", detail: "die(string|int $message = \"\"): never", documentation: "Equivalent to exit." },
  { label: "exit", detail: "exit(string|int $status = \"\"): never", documentation: "Outputs a message and terminates the current script." },
  { label: "sleep", detail: "sleep(int $seconds): int", documentation: "Delays execution." },
  { label: "usleep", detail: "usleep(int $microseconds): void", documentation: "Delays execution in microseconds." },
  { label: "class_exists", detail: "class_exists(string $class, bool $autoload = true): bool", documentation: "Checks if the class has been defined." },
  { label: "function_exists", detail: "function_exists(string $function): bool", documentation: "Checks if a function has been defined." },
  { label: "method_exists", detail: "method_exists(object|string $object_or_class, string $method): bool", documentation: "Checks if the class method exists." },
  { label: "property_exists", detail: "property_exists(object|string $object_or_class, string $property): bool", documentation: "Checks if the object or class has a property." },
  { label: "get_class", detail: "get_class(object $object = ?): string", documentation: "Returns the name of the class of an object." },
  { label: "instanceof", detail: "$object instanceof ClassName", documentation: "Determines whether a variable is an instantiated object of a given class." },
  { label: "array_key_first", detail: "array_key_first(array $array): int|string|null", documentation: "Gets the first key of an array." },
  { label: "array_key_last", detail: "array_key_last(array $array): int|string|null", documentation: "Gets the last key of an array." },
  { label: "password_hash", detail: "password_hash(string $password, string|int|null $algo, array $options = []): string", documentation: "Creates a password hash." },
  { label: "password_verify", detail: "password_verify(string $password, string $hash): bool", documentation: "Verifies that a password matches a hash." },
  { label: "hash", detail: "hash(string $algo, string $data, bool $binary = false, array $options = []): string", documentation: "Generates a hash value." },
  { label: "ctype_alpha", detail: "ctype_alpha(mixed $text): bool", documentation: "Checks if all characters are letters." },
  { label: "ctype_digit", detail: "ctype_digit(mixed $text): bool", documentation: "Checks if all characters are digits." },
  { label: "array_is_list", detail: "array_is_list(array $array): bool", documentation: "Checks whether a given array is a list." },
];

export function registerPhpCompletions(monaco: Monaco): void {
  monaco.languages.registerCompletionItemProvider("php", {
    provideCompletionItems(model: import("monaco-editor").editor.ITextModel, position: import("monaco-editor").Position) {
      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };

      const suggestions = PHP_FUNCTIONS.map((fn) => ({
        label: fn.label,
        kind: monaco.languages.CompletionItemKind.Function,
        insertText: fn.label,
        detail: fn.detail,
        documentation: fn.documentation,
        range,
      }));

      return { suggestions };
    },
  });
}
